/*
 * Migration: Create equipment table
 * Purpose: Store hardware equipment inventory with full audit trail
 * Tables affected: equipment (created)
 * Special notes:
 *   - equipment_id auto-generated via trigger (format EQ-YYYY-NNNNN)
 *   - Full audit trail with created_by/updated_by references
 *   - Unique constraints on equipment_id and serial_number
 *   - RLS enabled, policies defined in separate migration
 */

-- create equipment table for hardware inventory management
-- includes comprehensive metadata and full audit trail
create table equipment (
  -- internal uuid primary key
  -- used for foreign key relationships
  id uuid primary key default gen_random_uuid(),
  
  -- human-readable unique equipment identifier
  -- format: EQ-YYYY-NNNNN (e.g., EQ-2024-00001)
  -- automatically generated by trigger before insert
  equipment_id varchar(15) unique not null,
  
  -- equipment name/title
  -- must not be empty (minimum 1 character)
  name varchar(100) not null check (length(name) >= 1),
  
  -- equipment category from predefined enum
  -- helps with filtering and reporting
  category equipment_category not null,
  
  -- manufacturer/vendor name
  manufacturer varchar(100) not null,
  
  -- model name or number
  model varchar(100) not null,
  
  -- unique serial number from manufacturer
  -- must be unique across all equipment
  serial_number varchar(100) unique not null,
  
  -- optional detailed description
  -- use for additional specs or notes
  description text,
  
  -- optional physical location
  -- e.g., "Building A, Room 123" or "Warehouse shelf B5"
  location varchar(200),
  
  -- optional purchase date
  -- useful for warranty tracking and depreciation
  purchase_date date,
  
  -- audit trail: when was this equipment record created
  created_at timestamptz not null default now(),
  
  -- audit trail: which user created this equipment record
  -- references profiles table, not auth.users directly
  created_by uuid not null references profiles(id),
  
  -- audit trail: when was this equipment record last modified
  -- automatically updated by trigger
  updated_at timestamptz not null default now(),
  
  -- audit trail: which user last modified this equipment record
  -- references profiles table, not auth.users directly
  updated_by uuid not null references profiles(id)
);

-- enable row level security on equipment table
-- policies will be defined in a separate migration
alter table equipment enable row level security;

-- create index on created_at for sorting equipment list by creation date (newest first)
create index idx_equipment_created_at on equipment(created_at desc);

-- create index on category for filtering equipment by type
create index idx_equipment_category on equipment(category);

-- create index on created_by for filtering equipment by creator
create index idx_equipment_created_by on equipment(created_by);

-- add comments to table and columns for documentation
comment on table equipment is 'Hardware equipment inventory with full audit trail';
comment on column equipment.id is 'Internal UUID primary key';
comment on column equipment.equipment_id is 'Human-readable unique ID in format EQ-YYYY-NNNNN';
comment on column equipment.name is 'Equipment name/title, minimum 1 character';
comment on column equipment.category is 'Equipment category from predefined enum';
comment on column equipment.serial_number is 'Manufacturer serial number, must be unique';
comment on column equipment.created_by is 'User who created this equipment record';
comment on column equipment.updated_by is 'User who last modified this equipment record';
